CREATE DATABASE IF NOT EXISTS QuanLyVatTu;
USE QuanLyVatTu;

-- 1. Bảng Phiếu Xuất
CREATE TABLE PHIEUXUAT (
    SoPX VARCHAR(20) PRIMARY KEY,
    NgayXuat DATETIME NOT NULL
);

-- 2. Bảng Phiếu Nhập
CREATE TABLE PHIEUNHAP (
    SoPN VARCHAR(20) PRIMARY KEY,
    NgayNhap DATETIME NOT NULL
);

-- 3. Bảng Vật Tư
CREATE TABLE VATTU (
    MaVTU VARCHAR(20) PRIMARY KEY,
    TenVTU VARCHAR(100) NOT NULL
);

-- 4. Bảng Nhà Cung Cấp
CREATE TABLE NHACC (
    MaNCC VARCHAR(20) PRIMARY KEY,
    TenNCC VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(255)
);

-- 5. Bảng Số Điện Thoại Nhà Cung Cấp (Thuộc tính đa trị)
CREATE TABLE NHACC_SDT (
    MaNCC VARCHAR(20),
    SDT VARCHAR(15),
    PRIMARY KEY (MaNCC, SDT),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC) ON DELETE CASCADE
);

-- 6. Bảng Đơn Đặt Hàng
CREATE TABLE DONDH (
    SoDH VARCHAR(20) PRIMARY KEY,
    NgayDH DATETIME NOT NULL,
    MaNCC VARCHAR(20),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);

-- 7. Bảng Chi Tiết Phiếu Xuất
CREATE TABLE CT_PHIEUXUAT (
    SoPX VARCHAR(20),
    MaVTU VARCHAR(20),
    DGXuat DECIMAL(12,2) CHECK (DGXuat > 0),
    SLXuat INT CHECK (SLXuat > 0),
    PRIMARY KEY (SoPX, MaVTU),
    FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

-- 8. Bảng Chi Tiết Phiếu Nhập
CREATE TABLE CT_PHIEUNHAP (
    SoPN VARCHAR(20),
    MaVTU VARCHAR(20),
    DGNhap DECIMAL(12,2) CHECK (DGNhap > 0),
    SLNhap INT CHECK (SLNhap > 0),
    PRIMARY KEY (SoPN, MaVTU),
    FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

-- 9. Bảng Chi Tiết Đơn Đặt Hàng
CREATE TABLE CT_DONDH (
    SoDH VARCHAR(20),
    MaVTU VARCHAR(20),
    PRIMARY KEY (SoDH, MaVTU),
    FOREIGN KEY (SoDH) REFERENCES DONDH(SoDH),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);
