CREATE DATABASE IF NOT EXISTS quan_ly_don_hang;
USE quan_ly_don_hang;

-- 1. Bảng Đơn vị khách
CREATE TABLE DV_KHACH (
    MaDV VARCHAR(20) PRIMARY KEY,
    TenDV VARCHAR(250) NOT NULL,
    DiaChi VARCHAR(255),
    DienThoai VARCHAR(20)
);

-- 2. Bảng Hàng
CREATE TABLE HANG (
    MaHang VARCHAR(20) PRIMARY KEY,
    TenHang VARCHAR(250) NOT NULL,
    DvTinh VARCHAR(50),
    MoTaHang TEXT
);

-- 3. Bảng Người đặt
CREATE TABLE NGUOI_DAT (
    MaSoND VARCHAR(20) PRIMARY KEY,
    HoTenND VARCHAR(100) NOT NULL,
    MaDV VARCHAR(20),
    FOREIGN KEY (MaDV) REFERENCES DV_KHACH(MaDV)
);

-- 4. Bảng Người nhận
CREATE TABLE NGUOI_NHAN (
    MaSoNN VARCHAR(20) PRIMARY KEY,
    HoTenNN VARCHAR(100) NOT NULL,
    MaDV VARCHAR(20),
    FOREIGN KEY (MaDV) REFERENCES DV_KHACH(MaDV)
);

-- 5. Bảng Người giao
CREATE TABLE NGUOI_GIAO (
    MaSoNG VARCHAR(20) PRIMARY KEY,
    HoTenNG VARCHAR(100) NOT NULL
);

-- 6. Bảng Nơi giao
CREATE TABLE NOI_GIAO (
    MaSoDDG VARCHAR(20) PRIMARY KEY,
    TenNoiGiao VARCHAR(255) NOT NULL
);

-- 7. Bảng Đơn đặt hàng
CREATE TABLE DON_DAT_HANG (
    SoDH VARCHAR(20) PRIMARY KEY,
    NgayDat DATE,
    MaSoND VARCHAR(20),
    FOREIGN KEY (MaSoND) REFERENCES NGUOI_DAT(MaSoND)
);

-- 8. Chi tiết Đơn đặt hàng
CREATE TABLE CHI_TIET_DON_HANG (
    SoDH VARCHAR(20),
    MaHang VARCHAR(20),
    SoLuong INT,
    PRIMARY KEY (SoDH, MaHang),
    FOREIGN KEY (SoDH) REFERENCES DON_DAT_HANG(SoDH),
    FOREIGN KEY (MaHang) REFERENCES HANG(MaHang)
);

-- 9. Bảng Phiếu giao hàng
CREATE TABLE PHIEU_GIAO_HANG (
    SoPG VARCHAR(20) PRIMARY KEY,
    NgayGiao DATE,
    MaSoNG VARCHAR(20),
    MaSoNN VARCHAR(20),
    MaSoDDG VARCHAR(20),
    FOREIGN KEY (MaSoNG) REFERENCES NGUOI_GIAO(MaSoNG),
    FOREIGN KEY (MaSoNN) REFERENCES NGUOI_NHAN(MaSoNN),
    FOREIGN KEY (MaSoDDG) REFERENCES NOI_GIAO(MaSoDDG)
);

-- 10. Chi tiết Giao hàng
CREATE TABLE CHI_TIET_GIAO_HANG (
    SoPG VARCHAR(20),
    MaHang VARCHAR(20),
    SoLuongGiao INT,
    DonGia DECIMAL(12,2),
    PRIMARY KEY (SoPG, MaHang),
    FOREIGN KEY (SoPG) REFERENCES PHIEU_GIAO_HANG(SoPG),
    FOREIGN KEY (MaHang) REFERENCES HANG(MaHang)
);